artifacts_root: artifacts

data_ingestion: data

data_validation:
  root_dir: artifacts/ data_validation
  STATUS_FILE: artifacts/status.txt
  ALL_REQUIRED_FILES: ["train", "test", "validation"]

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/dataset/Sherlock Holmes.txt
  tokenizer_name: sherlock_tokenizer

